In [1]:
#pip install pandas

In [2]:
import pandas as pd

In [3]:
a=[10,20,30,40,50]
pd.Series(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
b=[3.4,6.7,7.8]
pd.Series(b)

0    3.4
1    6.7
2    7.8
dtype: float64

In [5]:
c=["python","java"]
pd.Series(c)

0    python
1      java
dtype: object

In [6]:
d=[4+7j,3+8j]
pd.Series(d)

0    4.0+7.0j
1    3.0+8.0j
dtype: complex128

In [7]:
pd.Series(a,index=["i","ii","iii","iv","v"])

i      10
ii     20
iii    30
iv     40
v      50
dtype: int64

In [8]:
data=pd.DataFrame({"name":["rajendra","rajesh","rajeev"],"marks":[60,70,80]})
data

       name  marks
0  rajendra     60
1    rajesh     70
2    rajeev     80

In [9]:
data1=pd.DataFrame({"names":["pooja","vara"],"mailid":["p@codegnan.com","v@gmail.com"],"salary":[6848936434,648364363]})
data1

   names          mailid      salary
0  pooja  p@codegnan.com  6848936434
1   vara     v@gmail.com   648364363

In [12]:
d=pd.read_csv("food.csv")
d

                 Food name      Restaurant
0              Veg Biryani  Little village
1        Paneer fried rice              F2
2             palak paneer          Ismail
3         Mushroom biryani    Rusted Spoon
4             French fries       Ice Magic
5                Ice cream      creamstone
6                    pizza         Dominos
7                 Panipuri         Gundala
8  Pressure cooker biryani       Our place
9                 sandwich          zomato

In [13]:
d.columns

Index(['Food name', 'Restaurant'], dtype='object')

In [14]:
d.shape

(10, 2)

In [18]:
d2=pd.read_csv("spotify.csv")
d2

,track_id,track_name,artist_name,year,popularity,artwork_url,album_name,acousticness,danceability,duration_ms,...,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,track_url,language
0,2r0ROhr7pRN4MXDMT1fEmd,"Leo Das Entry (From ""Leo"")",Anirudh Ravichander,2024,59,https://i.scdn.co/image/ab67616d0000b273ce9c65...,"Leo Das Entry (From ""Leo"")",0.02410,0.753,97297.0,...,8.0,0.1000,-5.994,0.0,0.1030,110.997,4.0,0.459,https://open.spotify.com/track/2r0ROhr7pRN4MXD...,Tamil
1,4I38e6Dg52a2o2a8i5Q5PW,AAO KILLELLE,"Anirudh Ravichander, Pravin Mani, Vaishali Sri...",2024,47,https://i.scdn.co/image/ab67616d0000b273be1b03...,AAO KILLELLE,0.08510,0.780,207369.0,...,10.0,0.0951,-5.674,0.0,0.0952,164.995,3.0,0.821,https://open.spotify.com/track/4I38e6Dg52a2o2a...,Tamil
2,59NoiRhnom3lTeRFaBzOev,Mayakiriye Sirikiriye - Orchestral EDM,"Anirudh Ravichander, Anivee, Alvin Bruno",2024,35,https://i.scdn.co/image/ab67616d0000b27334a1dd...,Mayakiriye Sirikiriye (Orchestral EDM),0.03110,0.457,82551.0,...,2.0,0.0831,-8.937,0.0,0.1530,169.996,4.0,0.598,https://open.spotify.com/track/59NoiRhnom3lTeR...,Tamil
3,5uUqRQd385pvLxC8JX3tXn,Scene Ah Scene Ah - Experimental EDM Mix,"Anirudh Ravichander, Bharath Sankar, Kabilan, ...",2024,24,https://i.scdn.co/image/ab67616d0000b27332e623...,Scene Ah Scene Ah (Experimental EDM Mix),0.22700,0.718,115831.0,...,7.0,0.1240,-11.104,1.0,0.4450,169.996,4.0,0.362,https://open.spotify.com/track/5uUqRQd385pvLxC...,Tamil
4,1KaBRg2xgNeCljmyxBH1mo,Gundellonaa X I Am A Disco Dancer - Mashup,"Anirudh Ravichander, Benny Dayal, Leon James, ...",2024,22,https://i.scdn.co/image/ab67616d0000b2735a59b6...,Gundellonaa X I Am a Disco Dancer (Mashup),0.01530,0.689,129621.0,...,7.0,0.3450,-9.637,1.0,0.1580,128.961,4.0,0.593,https://open.spotify.com/track/1KaBRg2xgNeCljm...,Tamil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62312,3eHDwMQYPEziy2DWRBNoLv,Sani - G.O.A.T Remix,"Arvind Raj, Sheezay, Music Kitchen, FSPROD Vin...",2021,30,https://i.scdn.co/image/ab67616d0000b273819d23...,Sani (G.O.A.T Remix),0.08490,0.877,359718.0,...,7.0,0.1100,-11.458,1.0,0.3530,100.024,4.0,0.504,https://open.spotify.com/track/3eHDwMQYPEziy2D...,Tamil
62313,5hHtCqkNv5eo99OrEFFcgS,Life of Bachelor,"A H Kaashif, Navakkarai Naveen Prabanjam, Asal...",2021,30,https://i.scdn.co/image/ab67616d0000b2736cd651...,Bachelor (Original Motion Picture Soundtrack),0.07880,0.833,154364.0,...,8.0,0.2670,-5.061,1.0,0.0813,110.041,4.0,0.524,https://open.spotify.com/track/5hHtCqkNv5eo99O...,Tamil
62314,08foF9YHgKmIgOy3xMWRZy,Yo Baby,"Rakesh Ambigapathy, Asal Kolaar, MC Vickey",2021,18,https://i.scdn.co/image/ab67616d0000b27300da25...,Yo Baby,0.00918,0.842,234000.0,...,7.0,0.0790,-5.855,1.0,0.1370,122.038,4.0,0.669,https://open.spotify.com/track/08foF9YHgKmIgOy...,Tamil
62315,2wLFbVlQGKJSd9lwzwL47F,Fast Fast Vadiley,"Asal Kolaar, Priyadarshan Balasubramanian",2021,1,https://i.scdn.co/image/ab67616d0000b273e051e1...,Arjuna Phalguna,0.10100,0.682,180807.0,...,1.0,0.3200,-6.061,1.0,0.2850,74.993,4.0,0.439,https://open.spotify.com/track/2wLFbVlQGKJSd9l...,Tamil
62316,5OYxwYeFfumMTAoAdVeet3,"Moonu Moonu Moonu (From ""3:33"")","Harshavardhan Rameshwar, G. V. Prakash, Dharma...",2021,1,https://i.scdn.co/image/ab67616d0000b273efd671...,"Moonu Moonu Moonu (From ""3:33"")",0.18600,0.817,202667.0,...,6.0,0.3780,-7.353,0.0,0.1170,89.975,4.0,0.837,https://open.spotify.com/track/5OYxwYeFfumMTAo...,Tamil

In [19]:
d2.shape

(62317, 22)